name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Bazel
      uses: bazelbuild/setup-bazel@v1

    - name: Build
      run: bazel build //...

    - name: Test
      run: bazel test //...

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run SAST
      uses: github/codeql-action/analyze@v2

  docker:
    needs: [build, security]
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
